/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lenguajes.final_project.frontend.windows;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lenguajes.final_project.backend.reports.ReportesExporter;
import lenguajes.final_project.backend.token.Token;

/**
 *
 * @author antho
 */
public class Reporte extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo1;
    private DefaultTableModel modelo2;
    private ArrayList<Token> todosLosTokens;
    
    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        String[] columnas1 = {"Nombre", "Lexema", "Fila", "Columna"};
        String[] columnas2 = {"Error", "Posicion fila", "Posicion columna"};

        modelo1 = new DefaultTableModel(columnas1, 0);
        modelo2 = new DefaultTableModel(columnas2, 0);

        table_tokens.setModel(modelo1);
        table_errores.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_tokens = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_errores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        table_tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tokens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(table_tokens);

        table_errores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_errores);

        jButton1.setText("Exportar reportes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReportesExporter exporter = new ReportesExporter();
        exporter.exportarTokensValidos(todosLosTokens);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void llenarTokens(List<Token> tokens, List<Token> tokensError, ArrayList<Token> todos) {
        this.todosLosTokens = todos;
        if (!tokens.isEmpty()) {
            for (Token token : tokens) {
                modelo1.addRow(new Object[]{token.getTipo().name(), token.getLexema(), token.getPosicion().getLINEA(), token.getPosicion().getCOLUMNA()});
            }
        }
        
        if (!tokensError.isEmpty()) {
            for (Token token : tokensError) {
                modelo2.addRow(new Object[]{token.getLexema(), token.getPosicion().getLINEA(), token.getPosicion().getCOLUMNA()});
            }
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_errores;
    private javax.swing.JTable table_tokens;
    // End of variables declaration//GEN-END:variables
}
